# Generated by Django 2.0.5 on 2018-05-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Musername', models.CharField(max_length=50)),
                ('Mfirst_name', models.CharField(max_length=30)),
                ('Mlast_name', models.CharField(max_length=30)),
                ('Memail', models.EmailField(max_length=254)),
                ('Mpassword1', models.CharField(max_length=20)),
                ('Mpassword2', models.CharField(max_length=20)),
            ],
        ),
    ]
