# Generated by Django 2.0.5 on 2018-05-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupmodel',
            old_name='Memail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='Mfirst_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='Mlast_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='Mpassword1',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='Mpassword2',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='Musername',
            new_name='username',
        ),
    ]
