# Generated by Django 2.0.5 on 2018-05-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='date',
            new_name='date_added',
        ),
    ]
