# Generated by Django 2.0.5 on 2018-05-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0003_auto_20180518_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='descripation',
            new_name='description',
        ),
    ]
